---
- name: install cm default jdk
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  when: usecmjava == true
  with_items:
    - oracle-j2sdk1.7
    - unzip

- name: Copy JCE unlimited policy
  copy:
    src: UnlimitedJCEPolicyJDK7.zip
    dest: "{{ tmp_dir }}/UnlimitedJCEPolicyJDK7.zip"

- name: Unzip JCE unlimited policy files
  unarchive:
    src: "{{ tmp_dir }}/UnlimitedJCEPolicyJDK7.zip"
    dest: "{{ tmp_dir }}"
    copy: no

- name: Install local_policy.jar
  copy:
    src: "{{ tmp_dir }}/UnlimitedJCEPolicy/local_policy.jar"
    dest: /usr/java/jdk1.7.0_67-cloudera/jre/lib/security/local_policy.jar
    backup: yes
    remote_src: True

- name: Install US_export_policy.jar
  copy:
    src: "{{ tmp_dir }}/UnlimitedJCEPolicy/US_export_policy.jar"
    dest: /usr/java/jdk1.7.0_67-cloudera/jre/lib/security/US_export_policy.jar
    backup: yes
    remote_src: True

- name: Cleanup tmp files
  file:
    path="{{ tmp_dir }}/{{ item }}"
    state=absent
  with_items:
    - UnlimitedJCEPolicy
    - UnlimitedJCEPolicyJDK7.zip
  ignore_errors: True
